#!/usr/bin/env python3
"""Inspect the checked-out Cosmos + RoboLab source and derive the served contract.

Writes `docs/generated/baseline_contract_derived.md`. It does NOT write
`docs/baseline_contract.md`: that document is hand-verified, ~10x longer, and carries
evidence no regex can derive. This script refuses to overwrite any file it did not
generate (see GENERATED_MARKER) — `make contract` used to destroy it.

Use it as a staleness check: if a value here disagrees with the hand-verified contract,
one of the two is out of date and the source is the tie-breaker.

Reads:
  the selected substrate's policy-server module (see configs/substrates.yaml;
  `COSMOS_SUBSTRATE=efficient_imagination` derives the contract for the fork instead)
  third_party/RoboLab/policies/cosmos3/run.py
  (optionally) a locally cached Cosmos3-Nano-Policy-DROID config.json under HF_HOME

Extracts:
  - default policy server port
  - default action denoising steps
  - default action chunk size
  - default conditioning FPS
  - default action dimension
  - open-loop horizon (client)
  - decode_video default
  - whether the server-side call returns both samples['action'] and samples['vision']

Any value it can't find is written as "UNKNOWN — inspect manually" with a
pointer to the file. This script never guesses.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from action_refresh.config import ResolvedSubstrate, resolve_substrate  # noqa: E402

CLIENT_PY = REPO_ROOT / "third_party" / "RoboLab" / "policies" / "cosmos3" / "client.py"

#: Marker written into every file this script generates. `main()` refuses to overwrite a
#: file that lacks it, because the default target used to be `docs/baseline_contract.md` —
#: a 239-line hand-verified document that this 25-line derivation would silently replace.
GENERATED_MARKER = "<!-- generated by scripts/derive_baseline_contract.py — do not hand-edit -->"


def _substrate() -> ResolvedSubstrate:
    """The tree whose contract we are deriving.

    `require_venv=False`: this script only reads source text, so it is useful on a
    freshly cloned substrate before anything is installed.
    """
    return resolve_substrate(repo_root=REPO_ROOT, require_venv=False)


def _read(p: Path) -> str:
    return p.read_text(errors="replace") if p.is_file() else ""


def field_default(text: str, name: str) -> str | None:
    """Value of a `name: type = default` declaration, resolving one level of constant.

    Anchored per-line and to the declaration form on purpose. The previous patterns used
    `[^=]*`, which is a negated class and therefore spans NEWLINES: `port[^=]*=[^)\d]*(\d+)`
    matched the "port" inside `import`, ran to the next `=` several lines below, and reported
    the server's default port as 3. `num_steps` was wrong the same way (5, against a true 4).
    Wrong-but-plausible is worse than UNKNOWN here, since these values define the baseline.
    """
    m = re.search(
        rf"^\s*{re.escape(name)}\s*:\s*[^=\n]+=\s*([^\n#]+?)\s*$",
        text,
        re.MULTILINE,
    )
    if not m:
        return None
    val = m.group(1).strip()
    # `True`/`False`/`None` are literals, not constants to chase. Without this they look like
    # identifiers, fail the constant lookup, and get reported as UNKNOWN — which is how
    # `decode_video: bool = False` came out unknown even though it is stated plainly.
    if val in ("True", "False", "None"):
        return val
    # Defaults are often module constants (`_DEFAULT_ACTION_CHUNK_SIZE`). Resolve exactly one
    # hop; anything deeper is reported as UNKNOWN rather than guessed at.
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", val):
        c = re.search(rf"^{re.escape(val)}\s*=\s*([^\n#]+?)\s*$", text, re.MULTILINE)
        if not c:
            return None
        val = c.group(1).strip()
    if val.startswith("pydantic.Field") or val.endswith("("):
        return None
    return val.strip("\"'")


def const(text: str, name: str) -> str | None:
    """Value of a module-level `NAME = literal`."""
    m = re.search(rf"^{re.escape(name)}\s*=\s*([^\n#]+?)\s*$", text, re.MULTILINE)
    return m.group(1).strip().strip("\"'") if m else None


def inspect_server(text: str, server_py: Path) -> dict[str, object]:
    fields = (
        "port", "host", "num_steps", "action_chunk_size", "conditioning_fps",
        "decode_video", "guidance", "shift", "seed", "deterministic_seed",
        "resolution", "vision_frames", "checkpoint_path", "hf_revision",
        "image_height", "image_width", "use_state", "history_length", "domain_name",
    )
    out: dict[str, object] = {f: field_default(text, f) for f in fields}
    out["returns_action"] = "samples['action']" in text or 'samples["action"]' in text
    out["returns_vision"] = "samples['vision']" in text or 'samples["vision"]' in text
    out["source_file"] = str(server_py.relative_to(REPO_ROOT))
    return out


def inspect_client(text: str) -> dict[str, object]:
    """The client's open-loop horizon.

    It is a CLASS ATTRIBUTE (`OPEN_LOOP_HORIZON = 32`) in `policies/cosmos3/client.py`, not
    an argparse default in `run.py` — which is why the earlier version of this script reported
    it UNKNOWN while the hand-verified contract had 32 all along.
    """
    return {
        "open_loop_horizon_default": const(text, "    OPEN_LOOP_HORIZON")
        or field_default(text, "OPEN_LOOP_HORIZON")
        or (re.search(r"^\s*OPEN_LOOP_HORIZON\s*=\s*(\d+)", text, re.MULTILINE) or [None, None])[1],
        "horizon_is_configurable": "_resolve_open_loop_horizon" in text,
        "source_file": str(CLIENT_PY.relative_to(REPO_ROOT)),
    }


def try_read_hf_config() -> dict[str, object]:
    """Best-effort read of the model's config.json from HF cache."""
    import os
    hf = os.environ.get("HF_HOME") or os.path.expanduser("~/.cache/huggingface")
    for cand in Path(hf).rglob("Cosmos3-Nano-Policy-DROID*/**/config.json"):
        try:
            c = json.loads(cand.read_text())
            return {
                "hf_config_path": str(cand),
                "action_dim": c.get("action_dim"),
                "conditioning_fps": c.get("conditioning_fps") or c.get("fps"),
                "denoising_steps": c.get("num_denoising_steps") or c.get("denoising_steps"),
                "action_chunk": c.get("action_chunk_size") or c.get("chunk_size"),
                "raw_keys": list(c.keys()),
            }
        except Exception:
            continue
    return {"hf_config_path": None}


def render(server: dict, client: dict, hf: dict, sub: ResolvedSubstrate) -> str:
    def cell(v: object) -> str:
        return f"`{v}`" if v not in (None, "unknown", "UNKNOWN") else "**UNKNOWN — inspect manually**"

    def dump(d: dict, source_key: str) -> str:
        return "\n".join(f"- **{k}**: {cell(v)}" for k, v in d.items() if k != source_key)

    dirty = " **(DIRTY TREE)**" if sub.dirty else ""
    return f"""{GENERATED_MARKER}
# Baseline contract (derived)

**This file is generated.** The authoritative, hand-verified contract is
`docs/baseline_contract.md`, which carries evidence this script cannot derive (transport
details, tensor shapes, the JSON-prompt finding). Use this one to check whether the source
still declares what that document claims — a disagreement means one of them is stale.

Derived from checked-out source. Every value here must be *observed*, not
assumed. Anything marked UNKNOWN needs manual inspection before we run
the baseline.

**Substrate**: `{sub.name}` — `{sub.source_name}` @ `{(sub.commit or "unknown")[:12]}`{dirty}

Two substrates exist and their server contracts need not agree, so this document
describes only the one named above. Regenerate with `COSMOS_SUBSTRATE=...` to derive
another; the differences are the substrate audit.

## Server (`{server.get('source_file')}`)
{dump(server, 'source_file')}

## Client (`{client.get('source_file')}`)
{dump(client, 'source_file')}

## HF model config (`{hf.get('hf_config_path')}`)
{dump({k: v for k, v in hf.items() if k != 'hf_config_path'}, '')}

## Critical detail

`decode_video=False` is NOT equivalent to "no visual imagination". It only
disables VAE decoding. Whether the joint diffusion transformer still
generates vision-latent tokens must be verified in the compute anatomy
(`docs/compute_anatomy.md`). Do NOT design cache/spatial methods before
that answer is known.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    # NOT docs/baseline_contract.md. That file is hand-verified and 10x longer than anything
    # derivable from regexes; writing there by default meant `make contract` destroyed it.
    ap.add_argument("--out", default=str(REPO_ROOT / "docs" / "generated" / "baseline_contract_derived.md"))
    ap.add_argument(
        "--force",
        action="store_true",
        help="overwrite the target even if it was not generated by this script",
    )
    ap.add_argument("--check", action="store_true", help="print to stdout, write nothing")
    args = ap.parse_args()

    sub = _substrate()
    server = inspect_server(_read(sub.server_file), sub.server_file)
    client = inspect_client(_read(CLIENT_PY))
    hf = try_read_hf_config()
    doc = render(server, client, hf, sub)

    if args.check:
        print(doc)
        return 0

    out = Path(args.out)
    if out.exists() and GENERATED_MARKER not in out.read_text(errors="replace") and not args.force:
        print(
            f"refusing to overwrite {out}: it exists and was not generated by this script.\n"
            f"  A hand-written document is not a derivation target. Either point --out at a\n"
            f"  generated path (default: docs/generated/baseline_contract_derived.md), use\n"
            f"  --check to print instead, or pass --force if you truly mean to replace it.",
            file=sys.stderr,
        )
        return 2

    unknown = [k for k, v in {**server, **client}.items() if v is None]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(doc)
    print(f"wrote {out} (substrate={sub.name} @ {(sub.commit or '')[:12]})")
    if unknown:
        # Not a failure: UNKNOWN is the honest output when a declaration moved. But it is
        # never silent, because an unnoticed UNKNOWN is how a stale contract survives.
        print(f"  {len(unknown)} value(s) UNKNOWN — inspect manually: {', '.join(sorted(unknown))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
